name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  environment:  # id of input
    description: 'environment to deploy'
    required: true
    default: 'development'
outputs:
  status: # output will be available to future steps 
    description: 'deploy status'
runs:
  using: 'node12'
  main: 'index.js'
